# Change Path

In [46]:
import pandas as pd

data_type = "train"

df = pd.read_csv(f"/home/thomas/Documents/Preprocessed/{data_type}/metadata.csv")

In [47]:
df.head()

,Unnamed: 0,label,duration_sec,path,sample_rate,class_code,date,MMSI,t1,c1,p1,sal,sv,t1_norm,c1_norm,p1_norm,sal_norm,sv_norm,sub_init,file_index
0,0,tug,1.0,/onc/07_classified_wav_files/inclusion_4000_ex...,32000,52.0,20160503,316005648.0,9.330329,3.292408,146.684360,30.266131,1484.024610,0.176308,0.780653,0.989737,0.916249,0.411784,673,0
1,1,passengership,1.0,/onc/07_classified_wav_files/inclusion_4000_ex...,32000,60.0,20161122,316001255.0,10.047558,3.419295,148.890808,30.939159,1487.511450,0.237935,0.869386,0.998063,0.969623,0.495566,750,1
2,2,tanker,1.0,/onc/07_classified_wav_files/inclusion_4000_ex...,32000,89.0,20160925,355320000.0,10.151994,3.421049,147.524463,30.868304,1487.781615,0.246908,0.870613,0.992907,0.964004,0.502057,695,2
3,3,other,1.0,/onc/07_classified_wav_files/inclusion_4000_ex...,32000,32.0,20160503,316003669.0,9.330013,3.302899,146.570566,30.373327,1484.152649,0.176281,0.787989,0.989307,0.924750,0.414860,742,3
4,4,cargo,1.0,/onc/07_classified_wav_files/inclusion_4000_ex...,32000,70.0,20160508,636017357.0,9.404962,3.291686,147.579680,30.195479,1484.229131,0.182721,0.780148,0.993115,0.910646,0.416698,535,4

In [48]:
def update_file_path(row):
    # Check if the path contains "vessel"
    if "vessel" in row["path"]:
        # Replace the old directory with the new one
        new_path = row["path"].replace(
            "/onc/07_classified_wav_files/inclusion_4000_exclusion_6000/vessel",
            "/home/thomas/Documents/classified_files/inclusion_4000_exclusion_6000/vessel",
        )
    elif "background" in row["path"]:
        # If the path does not contain "vessel", it could be background. You can handle it accordingly.
        # For example, you might want to keep the same path or replace it with another directory.
        new_path = row["path"].replace(
            "/onc/07_classified_wav_files/inclusion_4000_exclusion_6000/background",
            "/home/thomas/Documents/classified_files/inclusion_4000_exclusion_6000/background",
        )

    return new_path

In [49]:
df["path"] = df.apply(update_file_path, axis=1)
df = df[df["label"] != "other"]
df.head()

,Unnamed: 0,label,duration_sec,path,sample_rate,class_code,date,MMSI,t1,c1,p1,sal,sv,t1_norm,c1_norm,p1_norm,sal_norm,sv_norm,sub_init,file_index
0,0,tug,1.0,/home/thomas/Documents/classified_files/inclus...,32000,52.0,20160503,316005648.0,9.330329,3.292408,146.684360,30.266131,1484.024610,0.176308,0.780653,0.989737,0.916249,0.411784,673,0
1,1,passengership,1.0,/home/thomas/Documents/classified_files/inclus...,32000,60.0,20161122,316001255.0,10.047558,3.419295,148.890808,30.939159,1487.511450,0.237935,0.869386,0.998063,0.969623,0.495566,750,1
2,2,tanker,1.0,/home/thomas/Documents/classified_files/inclus...,32000,89.0,20160925,355320000.0,10.151994,3.421049,147.524463,30.868304,1487.781615,0.246908,0.870613,0.992907,0.964004,0.502057,695,2
4,4,cargo,1.0,/home/thomas/Documents/classified_files/inclus...,32000,70.0,20160508,636017357.0,9.404962,3.291686,147.579680,30.195479,1484.229131,0.182721,0.780148,0.993115,0.910646,0.416698,535,4
5,5,tug,1.0,/home/thomas/Documents/classified_files/inclus...,32000,52.0,20160801,367186040.0,10.110795,3.403708,147.971770,30.729459,1487.471016,0.243368,0.858486,0.994595,0.952993,0.494594,39,5

In [50]:
df.to_csv(f"/home/thomas/Documents/Preprocessed/{data_type}/metadata_updated.csv")

# Get number of classes

In [3]:
import pandas as pd

df = pd.read_csv(f"/home/thomas/Documents/Preprocessed/train/metadata.csv")
df.head()

,Unnamed: 0,label,duration_sec,path,sample_rate,class_code,date,MMSI,t1,c1,p1,sal,sv,t1_norm,c1_norm,p1_norm,sal_norm,sv_norm,sub_init,file_index
0,0,tug,1.0,/onc/07_classified_wav_files/inclusion_4000_ex...,32000,52.0,20160503,316005648.0,9.330329,3.292408,146.684360,30.266131,1484.024610,0.176308,0.780653,0.989737,0.916249,0.411784,673,0
1,1,passengership,1.0,/onc/07_classified_wav_files/inclusion_4000_ex...,32000,60.0,20161122,316001255.0,10.047558,3.419295,148.890808,30.939159,1487.511450,0.237935,0.869386,0.998063,0.969623,0.495566,750,1
2,2,tanker,1.0,/onc/07_classified_wav_files/inclusion_4000_ex...,32000,89.0,20160925,355320000.0,10.151994,3.421049,147.524463,30.868304,1487.781615,0.246908,0.870613,0.992907,0.964004,0.502057,695,2
3,3,other,1.0,/onc/07_classified_wav_files/inclusion_4000_ex...,32000,32.0,20160503,316003669.0,9.330013,3.302899,146.570566,30.373327,1484.152649,0.176281,0.787989,0.989307,0.924750,0.414860,742,3
4,4,cargo,1.0,/onc/07_classified_wav_files/inclusion_4000_ex...,32000,70.0,20160508,636017357.0,9.404962,3.291686,147.579680,30.195479,1484.229131,0.182721,0.780148,0.993115,0.910646,0.416698,535,4

In [4]:
counts = df["label"].value_counts()
print(counts)

label
tug              28382
passengership    28382
tanker           28382
other            28382
cargo            28382
background       28382
Name: count, dtype: int64

In [5]:
len(df)

170292

In [6]:
len(df) / 6

28382.0